services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: gym
      POSTGRES_PASSWORD: gym
      POSTGRES_DB: gym_gestion
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
